// generated by Fast Light User Interface Designer (fluid) version 1.0403

#include "cwsettings.h"
#include "gettext.h"
#ifndef gettext_noop
#  define gettext_noop(text) text
#endif
#include "confdialog.h"

Fl_Check_Button *btnCWSrcvTrack=(Fl_Check_Button *)0;

static void cb_btnCWSrcvTrack(Fl_Check_Button* o, void*) {
  progdefaults.CWtrack = o->value();
  btnCWrcvTrack->value(o->value());
  progdefaults.changed = true;
}

Fl_Check_Button *btnCWSuseSOMdecoding=(Fl_Check_Button *)0;

static void cb_btnCWSuseSOMdecoding(Fl_Check_Button* o, void*) {
  progdefaults.CWuseSOMdecoding = o->value();
  btnCWuseSOMdecoding->value(o->value());

  progdefaults.changed = true;
}

Fl_Check_Button *btnCWSmfilt=(Fl_Check_Button *)0;

static void cb_btnCWSmfilt(Fl_Check_Button* o, void*) {
  progdefaults.CWmfilt = o->value();
  btnCWmfilt->value(o->value());
  if (active_modem == cw_modem)
    active_modem->reset_rx_filter();
  progdefaults.changed = true;
}

Fl_Counter2 *cntCWSbandwidth=(Fl_Counter2 *)0;

static void cb_cntCWSbandwidth(Fl_Counter2* o, void*) {
  progdefaults.CWbandwidth = (int)o->value();
  cntCWbandwidth->value(o->value());
  if (active_modem == cw_modem)
    active_modem->reset_rx_filter();
  progdefaults.changed = true;
}

Fl_Choice *mnu_CWS_fillen=(Fl_Choice *)0;

static void cb_mnu_CWS_fillen(Fl_Choice* o, void*) {
  progdefaults.CW_fillen = o->value();
  mnu_CW_fillen->value(o->value());
  if (active_modem == cw_modem)
    active_modem->reset_rx_filter();
  progdefaults.changed = true;
}

Fl_Double_Window* make_cwsettings() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(854, 26);
    w = o; (void)w;
    o->box(FL_DOWN_BOX);
    { Fl_Check_Button* o = btnCWSrcvTrack = new Fl_Check_Button(4, 2, 120, 20, gettext("Track WPM"));
      btnCWSrcvTrack->tooltip(gettext("Automatic Rx speed tracking"));
      btnCWSrcvTrack->down_box(FL_DOWN_BOX);
      btnCWSrcvTrack->value(1);
      btnCWSrcvTrack->callback((Fl_Callback*)cb_btnCWSrcvTrack);
      o->value(progdefaults.CWtrack);
    } // Fl_Check_Button* btnCWSrcvTrack
    { Fl_Check_Button* o = btnCWSuseSOMdecoding = new Fl_Check_Button(125, 2, 120, 20, gettext("SOM decode"));
      btnCWSuseSOMdecoding->tooltip(gettext("Self Organizing Map Decoder"));
      btnCWSuseSOMdecoding->down_box(FL_DOWN_BOX);
      btnCWSuseSOMdecoding->value(1);
      btnCWSuseSOMdecoding->callback((Fl_Callback*)cb_btnCWSuseSOMdecoding);
      o->value(progdefaults.CWuseSOMdecoding);
    } // Fl_Check_Button* btnCWSuseSOMdecoding
    { Fl_Check_Button* o = btnCWSmfilt = new Fl_Check_Button(250, 2, 120, 20, gettext("Matched Filter"));
      btnCWSmfilt->tooltip(gettext("Matched Filter bandwidth"));
      btnCWSmfilt->down_box(FL_DOWN_BOX);
      btnCWSmfilt->value(1);
      btnCWSmfilt->callback((Fl_Callback*)cb_btnCWSmfilt);
      o->value(progdefaults.CWmfilt);
    } // Fl_Check_Button* btnCWSmfilt
    { Fl_Counter2* o = cntCWSbandwidth = new Fl_Counter2(380, 2, 120, 20, gettext("Bandwidth"));
      cntCWSbandwidth->tooltip(gettext("Range +/- wpm"));
      cntCWSbandwidth->box(FL_UP_BOX);
      cntCWSbandwidth->color(FL_BACKGROUND_COLOR);
      cntCWSbandwidth->selection_color(FL_INACTIVE_COLOR);
      cntCWSbandwidth->labeltype(FL_NORMAL_LABEL);
      cntCWSbandwidth->labelfont(0);
      cntCWSbandwidth->labelsize(14);
      cntCWSbandwidth->labelcolor(FL_FOREGROUND_COLOR);
      cntCWSbandwidth->minimum(50);
      cntCWSbandwidth->maximum(500);
      cntCWSbandwidth->step(5);
      cntCWSbandwidth->value(200);
      cntCWSbandwidth->callback((Fl_Callback*)cb_cntCWSbandwidth);
      cntCWSbandwidth->align(Fl_Align(FL_ALIGN_TOP));
      cntCWSbandwidth->when(FL_WHEN_CHANGED);
      o->value(progdefaults.CWbandwidth);
      o->labelsize(FL_NORMAL_SIZE);
      o->lstep(50);
    } // Fl_Counter2* cntCWSbandwidth
    { Fl_Choice* o = mnu_CWS_fillen = new Fl_Choice(510, 2, 72, 20, gettext("Fil\' Len\'"));
      mnu_CWS_fillen->tooltip(gettext("Filter length in samples"));
      mnu_CWS_fillen->down_box(FL_BORDER_BOX);
      mnu_CWS_fillen->callback((Fl_Callback*)cb_mnu_CWS_fillen);
      mnu_CWS_fillen->align(Fl_Align(FL_ALIGN_RIGHT));
      o->add("128|256|512|1024");
      o->value(progdefaults.CW_fillen);
    } // Fl_Choice* mnu_CWS_fillen
    { Fl_Group* o = new Fl_Group(650, 2, 200, 20);
      o->end();
      Fl_Group::current()->resizable(o);
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
