// generated by Fast Light User Interface Designer (fluid) version 1.0403

#ifndef cwsettings_h
#define cwsettings_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *btnCWSrcvTrack;
extern Fl_Check_Button *btnCWSuseSOMdecoding;
extern Fl_Check_Button *btnCWSmfilt;
#include "flslider2.h"
extern Fl_Counter2 *cntCWSbandwidth;
#include <FL/Fl_Choice.H>
extern Fl_Choice *mnu_CWS_fillen;
#include <FL/Fl_Group.H>
Fl_Double_Window* make_cwsettings();
#endif
